### PR TITLE
Update README.md charts to reflect recent updates

### PR DESCRIPTION
**Pull request by NotAlexNoyle**
Clarifies current device support

(all 64-bit devices minus iPhone 7/7+ and iPad Air 2)

### CODE REVIEW

**Comment by nullpixel1** [comment]
Dupe of #219, and #141 already adds it

**Comment by NotAlexNoyle** [comment]
My mistake. Closing.

**Comment by nullpixel1** [comment]
👍

**Comment by KILLCAMPER** [comment]
So Air pad 2 working ?

**Pull request closed without merging**
