### PR TITLE
Added compiling section

### PR DESCRIPTION
**Pull request by nullpixel1**
Also added:

- More to contribution section
- Guide on fixing IOKit issues
- Compiling section

### CODE REVIEW

**Comment by AppleBetas** [comment]
+1

**Comment by kpwn** [comment]
There is no need to download headers from 3rd parties when they are legally distributed with the OS X SDK. Not merging.

**Comment by nullpixel1** [comment]
@kpwn Will update that section, sec

**Comment by nullpixel1** [comment]
@kpwn Can you re-review this?

**Pull request closed without merging**
