### PR TITLE
iPhone 5s 10.2 Corrected Offsets

### PR DESCRIPTION
**Pull request by jtv7**
It seems rootvnode was calculated incorrectly, so these are the updated offsets.

### CODE REVIEW

**Comment by toniqyteza** [comment]
this won't still work for iPhone 5s right?

**Comment by jtv7** [comment]
@toniqyteza No

**Comment by 0neday** [comment]
@jtv7 thx your hard work, I will test on 5s 10.2

**Comment by jtv7** [comment]
@0neday It won't work, more is needed than just correct offsets

**Comment by Dason-g** [comment]
iphone 6 @jtv7

**Comment by vmunich** [comment]
Not working on the 5S.

**Comment by vmunich** [comment]
@dylanaraps I've compiled with this commit, as well as with the latest commit done by Luca, neither worked on the 5s. Can you explain the dislike?

**Comment by dylanaraps** [comment]
My bad, was lurking through the issues and thought you were another troll.

**Pull request closed without merging**
