### PR TITLE
all offsets for 10.x - 10.2 arm64

### PR DESCRIPTION
**Pull request by Mila432**

### CODE REVIEW

**Comment by AdibSadman** [comment]
Please add support to iPad Air 2 wifi thanks

**Comment by KILLCAMPER** [comment]
iPad Air 2  calluses if possible thanks

**Comment by nicogibbons** [comment]
I've already got the iPad Air 2 Wifi 10.2 offsets in the build

**Comment by 4taras4** [comment]
machine: iPhone6,1
2017-01-26 14:10:54.412875 yalu102[233:5161] found corruption 38203
2017-01-26 14:11:03.920133 yalu102[233:5161] found kernel text at fffffff027e04000
2017-01-26 14:11:03.922950 yalu102[233:5161] got tfp0 -> f07
2017-01-26 14:11:03.925414 yalu102[233:5161] found procs at fffffff004745428
2017-01-26 14:11:03.930776 yalu102[233:5161] seg: __TEXT
2017-01-26 14:11:03.930858 yalu102[233:5161] seg: __DATA_CONST
2017-01-26 14:11:03.930905 yalu102[233:5161] seg: __TEXT_EXEC
2017-01-26 14:11:03.930943 yalu102[233:5161] seg: __KLD
2017-01-26 14:11:03.930979 yalu102[233:5161] seg: __LAST
2017-01-26 14:11:03.931016 yalu102[233:5161] seg: __DATA
2017-01-26 14:11:03.931051 yalu102[233:5161] seg: __PRELINK_TEXT
2017-01-26 14:11:03.931088 yalu102[233:5161] seg: __PLK_TEXT_EXEC
2017-01-26 14:11:03.931124 yalu102[233:5161] seg: __PRELINK_DATA
2017-01-26 14:11:03.931161 yalu102[233:5161] seg: __PLK_DATA_CONST
2017-01-26 14:11:03.931253 yalu102[233:5161] seg: __PLK_LINKEDIT
2017-01-26 14:11:03.931301 yalu102[233:5161] seg: __PRELINK_INFO
2017-01-26 14:11:03.931339 yalu102[233:5161] seg: __LINKEDIT
2017-01-26 14:11:03.931376 yalu102[233:5161] fffffff026fbc000 - fffffff028698000
2017-01-26 14:11:04.002398 yalu102[233:5161] ffffffff03d9c000
2017-01-26 14:11:04.054366 yalu102[233:5161] fffffff027e655a0
2017-01-26 14:11:04.093758 yalu102[233:5161] pmap: fffffff028314850
2017-01-26 14:11:04.133869 yalu102[233:5161] got phys at 0 for virt fffffff019b5f000
2017-01-26 14:11:04.134028 yalu102[233:5161] found cpu 0
2017-01-26 14:11:04.134066 yalu102[233:5161] found physz: fffffff027e87000
2017-01-26 14:11:04.134109 yalu102[233:5161] found cpu 1
2017-01-26 14:11:04.134141 yalu102[233:5161] found physz: fffffff027e87000
2017-01-26 14:11:04.134198 yalu102[233:5161] fffffff027f8733c - fffffff027f8719c
2017-01-26 14:11:04.136071 yalu102[233:5161] ttbr0: 8024c5000 fffffff027e65590


 still crash

**Comment by liudayu** [comment]
@4taras4 OMG DO YOU READ ANY ISSUES BEFORE YOU POST ANYTHING HERE???
IT'S EVEN ON qwertyoruiop's WEBSITE, AS IT SAYS "YALU102 FOR 6S/SE AND IPAD PRO 10.0/10.1/10.2" YOU HAVE AN IPHONE 5S OF COURSE IT DOESN'T WORK
MORE DEVICES SUPPORT WILL COME SOON CAN YOU JUST WAIT AND BE PATIENT?

**Comment by tangalbert919** [comment]
@liudayu, calm down. We get it. The jailbreak community wants to be s*** with @kpwn.
He doesn't need to do this. He can just drop it, and then make the rest of us who forked this project do the work instead. Let's not start flame wars or be excitable here.
This pull request by @Mila432 is some nice work, but wouldn't it be easier to read and identify this for lower-level brainiacs of Apple devices to add an if statement for build numbers (like "iPhone8,1")?

**Comment by xNako** [comment]
Please, add support to iPad Mini 3

**Comment by 0x0luke** [comment]
Would you mind adding comments next to the offsets you've added to say which device/version they're for?

**Comment by 4taras4** [comment]
I checked  her pull request, works fine

**Comment by KILLCAMPER** [comment]
Thank you @nicogibbons  is that for just wifi or cellular as well as will test mine see if get same

**Comment by Mila432** [comment]
@tangalbert919  @0x0luke why this offsets are covering all devices ? If you don't understand this stay away

**Comment by liudayu** [comment]
@Mila432 oh nah they were just saying add `// Device + iOS version` after each offset, so it's easier for people know which is which :)

**Comment by jakeHq** [comment]
vouch for this shit.

**Comment by 0x0luke** [comment]
@Mila432 Don't be like that please, this is a team effort, knowing which offsets are for which device would be better than us having to find it manually in the kernel

**Comment by Mila432** [comment]
Ain't nobody has time for this shit to go through 200 ipsw's to get your device model ..

**Comment by jedieaston** [comment]
If we compile the jailbreak now, are these new offsets all that is required to get support on the rest of the devices?

**Comment by tangalbert919** [comment]
@Mila432 I understand this. There is one flaw though: The kernels between each device Apple releases aren't exactly the same. Sure, they might share the same processor (which is indicated at the end of the string), but does the iPhone 6s really have the same offsets as the iPad Pro?
If they are, that must mean you decompressed and disassembled the kernel, and you ended up getting the exact same results. You did do that, right?

**Comment by AGagarin** [comment]
как я могу найти оффсет для pad mini 2 c симкой ?

**Comment by DarknesGaming** [comment]
I failed to understand this. Looks like Russian.

**Comment by Mila432** [comment]
@tangalbert919 yea

Yalu logo

**Comment by RypeDub420** [comment]
Can someone please label every offset with what device it's for? Right now they mostly have a comment from @Mila432 but not describing what device they are for.

**Comment by Mila432** [comment]
@RypeDub420 again if you don't understand this stay out of here ..

**Comment by RypeDub420** [comment]
lol I understand that you have the device identifiers near the end of the strings @Mila432, I would just also like a comment for easy interpretation of the devices such as the wording iPhone 6+, iPad Mini Wifi, and so on.

**Comment by Mila432** [comment]
@RypeDub420 download all ipsw's, extract the kernel, decrypt it and check it

**Comment by RypeDub420** [comment]
What you have is this @Mila432:
        allproc_offset = 0x5ec478; /* @Mila432 */

What I am suggesting is to add this:
        allproc_offset = 0x5ec478; /* iPhone 7, iPhone 7+ @Mila432 */

As per: https://www.theiphonewiki.com/wiki/Bootrom

**Comment by mwoolweaver** [comment]
It would make it more uniform if it they where all either labeled or not labeled...

**Comment by Mila432** [comment]
@RypeDub420  Feel free to pr

**Comment by RypeDub420** [comment]
All you had to do was say that at first instead of assuming I didn't know what was going on.

I'm just calling for more details, literally as much as possible.

I don't believe i am at any fault with my request.

**Comment by RypeDub420** [comment]
Pull Request submitted.

**Pull request merged**
