### PR TITLE
Add offsets for iPhone 5s iOS 10.1.1

### PR DESCRIPTION
**Pull request by stefanstefan2001**
I hope that these are correct.

### CODE REVIEW

**Comment by jtv7** [comment]
What do you get when you run the command: nm kernelcache.decrypted | grep rootvnode

I get 0x5ae0b8 for rootvnode

**Comment by stefanstefan2001** [comment]
Yep, I got the same offset, but still it doesn't work for me

**Comment by jtv7** [comment]
Ok, I just wanted to make sure I was doing it correctly :).  And it doesn't work for me either, but I believe it was mentioned that for some devices there needs to be more changes than just different offsets.

**Comment by liudayu** [comment]
5s is not supported at this moment

**Comment by sql-93** [comment]
you must add at offsets.c iPhone 5s both gsm & global ( 6,1 & 6,2 ) for ios 10.1.1

**Comment by 4taras4** [comment]
Iphone 6,1 still without success

**Comment by skimaskngun** [comment]
If 5s gets fixed in 10.1.1 then theoretically it will support 10.2 soon I'm assuming

**Comment by stefanstefan2001** [comment]
closing this PR, because the offsets got merged

**Comment by jtv7** [comment]
Im not so sure this should be closed, I think the offsets merged (at least for this kernel) are incorrect (rootvnode)

**Pull request closed without merging**
