### PR TITLE
Instruction to ssh over USB with dropbear and Code Documentation

### PR DESCRIPTION
**Pull request by timonline**
Added a section for those who are asking about SSH over USB

### CODE REVIEW

**Comment by OGKevin** [comment]
There is already a tutorial on r/jailbreak reagrding ssh over usb  i think its better to dircet them there. I dont think allot of average users read the readme.

**Comment by timonline** [comment]
This one is a quick a dirty method since people don't seem to go to the r/jailbreak tutorial and ask here. At least we can tell them it's in the readme

**Comment by 0neday** [comment]
good instruction

**Comment by timonline** [comment]
@0neday, thank you

**Comment by ryanb93** [comment]
It seems like this README is growing in size with FAQs. We should enable the wiki for this project and put this sort of useful information in there instead.

**Comment by SuBLiNeR** [comment]
If it is okay, i did a tutorial on reddit. Maybe this helps more specific for most users as the iphonewiki is for the professionals ;) - https://redd.it/5r2mwr

**Pull request closed without merging**
