### PR TITLE
Add license to ReadMe

### PR DESCRIPTION
**Pull request by nerdtron123**

### CODE REVIEW

**Comment by tangalbert919** [comment]
@nerdtron23 knows about the license, but the license itself is not the "Anyone But Stefan Esser" license.

**Comment by bobbysn0w** [comment]
According to Luca's Yalu website, only Yalu B3 was licensed under ABSE licenses. Yalu102 Alpha release was licensed under the WTFPL licenses. Please close as this isn't necessary.

**Comment by Legitgamer264** [comment]
This license/addition, is not needed.

**Comment by semvoigt** [comment]
Does that mean that Stefan Esser finally opensourced his Capstone plugin for IDA?

Because I would love to check it out!

**Comment by nullpixel1** [comment]
@kpwn This isn't needed, and can be closed

**Pull request closed without merging**
