### PR TITLE
Added IO Framework

### PR DESCRIPTION
**Pull request by CrypticGit**
Fixes IO errors

### CODE REVIEW

**Comment by meyer9** [comment]
I don't believe this is allowed.

**Comment by nullpixel1** [comment]
You shouldn't be importing the IOKit framework: you should be importing it from your headeds

**Comment by CrypticGit** [comment]
@nullpixel1 it fixes all io errors just by dragging it in

**Comment by filfat** [comment]
There's this thing called the copyright law. Don't break it.

**Comment by CrypticGit** [comment]
I got this file from my Mac not from any site

**Comment by filfat** [comment]
@CrypticGit Doesn't mean it's not copyright protected https://github.com/kpwn/yalu102/pull/104/files#diff-5b17605bddd9cf476f043e70e94cfdfbR4.

@kpwn This should be closed.

**Pull request closed without merging**
