### PR TITLE
Automatically find IOKit

### PR DESCRIPTION
**Pull request by mologie**
This will symlink IOKit (and libkern's OSTypes.h) headers from the Xcode installation used to open the project into yalu102/include, unless the links already exist. Nothing is checked into the git repository and the user is free to still use his own copy if he so pleases.

### CODE REVIEW

**Comment by SuBLiNeR** [comment]
👍🏻

**Review by ghost — APPROVED** [review]

**Review by mrwulff — APPROVED** [review]

**Review by beren12 — APPROVED** [review]
Works great.

**Comment by RypeDub420** [comment]
Close this.

IOKit includes the "headers" you're looking for.

It is like Microsoft Visual C++ or .NET 4.0: it's bundled with the macOS SDK.

**Comment by mologie** [comment]
@RypeDub420: From your comment, I read that you seem to misunderstand the purpose of this PR. This does not add any headers to the project itself.

**Review by felipejfc — APPROVED** [review]
I've tested it and the PR makes total sense and works as expected

**Comment by timonline** [comment]
@mologie works perfectly. Thank you

**Comment by 0neday** [comment]
work fine, thx

**Comment by mologie** [comment]
qwertyoruiop was trolling us all along. IOKit is actually not used at all by yalu102. I feel shame now.

**Pull request closed without merging**
