### PR TITLE
Beta 4, 5 and 6 Link in README.md

### PR DESCRIPTION
**Pull request by Kizarr**
Updated the beta ipa links etc.

### CODE REVIEW

**Comment by nerdtron123** [comment]
beta 5 is broken, just put "Broken"
beta 4 is also broken.

**Comment by Kizarr** [comment]
Okay

**Comment by bronch** [comment]
Regarding the broken IPA links, just put "Broken" as simple text, not as links

**Comment by tjsreece** [comment]
Beta 4/5/6 links are _**not**_ broken. Here are the correct links

Beta 4:
[https://yalu.qwertyoruiop.com/yalu102_beta4.ipa](https://yalu.qwertyoruiop.com/yalu102_beta4.ipa
)
Beta 5:
[https://yalu.qwertyoruiop.com/yalu102_beta5.ipa](https://yalu.qwertyoruiop.com/yalu102_beta5.ipa
)
Beta 6:
[https://yalu.qwertyoruiop.com/yalu102_beta6.ipa](https://yalu.qwertyoruiop.com/yalu102_beta6.ipa
)

**Comment by nerdtron123** [comment]
@tjsreece i didn't say links were broken, beta4-5 are unstable/broken

**Comment by abjugard** [comment]
@tjsreece People are thumbing you down because you misunderstood the issue, you are however correct, and this is about the worst looking PR I have ever seen and should not be merged, 9 commits to change some wording in the readme, 6 of which contain typos? Are you kidding me?

**Pull request closed without merging**
