### PR TITLE
iPhone 6 10.1.1 and (fixed) 10.2 offsets

### PR DESCRIPTION
**Pull request by CodeyMoore**
Corrected iPhone 6 10.2 offsets and added iPhone 6 10.1.1 offsets

### CODE REVIEW

**Comment by X-s** [comment]
hi bro, thanks your work and can you compile a ipa shared here? many people want to test it. ths

**Comment by upal212** [comment]
Hey, an ipa would be appreciated.

**Comment by siddharth69** [comment]
Hi dude. An IPA would be much appreciated for this. Willing to test right away. And btw, great job!

**Comment by liudayu** [comment]
@X-s @upal212 @siddharth69 
**NO**, THIS JAILBREAK **DOESN'T SUPPORT** IPHONE 6 **YET**.

**Comment by siddharth69** [comment]
@liudayu Well, if the offsets are added, what would prevent the jailbreak from functioning?

**Comment by AppleBetas** [comment]
@siddharth69 Just to prove it, I tested this on my iPhone 6. It does not work. I don't know the exact requirements of getting it to work, but offsets aren't the only thing stopping it from functioning on 4k devices.

**Comment by siddharth69** [comment]
@AppleBetas Um, alrighty. Waiting for the official 4K devices support eagerly tho..

**Comment by meyer9** [comment]
ah the offsets were off? can you upload a success log?

**Comment by CodeyMoore** [comment]
I was aware that this jailbreak didn't (currently) support the iPhone 6, I only committed this because it adds and fixes offset(s) for this device when it's supported. People will have to wait patiently (like the rest of us) for qwertyoruiopz or marcograssi to add support.

**Comment by Mila432** [comment]
Why don't you scroll down https://github.com/CodeyMoore/yalu102/blob/91a5426306aa2d512e60b88814df72350bbf3c80/yalu102/offsets.c#L68

**Comment by CodeyMoore** [comment]
@Mila432 the rootvnode that i added is different...

**Comment by Mila432** [comment]
@CodeyMoore what kernel did you use for this

**Comment by CodeyMoore** [comment]
@Mila432 iPhone 6, iOS 10.1.1, kernalcache.release.n61 and iPhone 6, iOS 10.2, kernalcache.release.n61 Is that what you wanted to know?

**Comment by liudayu** [comment]
iPhone 6 is kernelcache.release.n71.................

**Comment by Mila432** [comment]
yep you have wrong offsets

Yalu logo

**Comment by CodeyMoore** [comment]
screen shot 2017-01-28 at 9 54 39 pm
screen shot 2017-01-28 at 9 54 24 pm

**Comment by Mila432** [comment]
That's not how you do it ...

**Comment by kpwn** [comment]
your offsets are wrong as per @Mila432

**Pull request closed without merging**
