### PR TITLE
This code supported 5s,6 ???

### PR DESCRIPTION
**Pull request by cloverdoser**
This code supported 5s,6 ???

### CODE REVIEW

**Comment by drakecsmall** [comment]
Is this tested?
If you have a compiled IPA I can run tests on my own iPhone 6.

**Comment by cloverdoser** [comment]
you can compile ipa and i test it

**Comment by TheNoim** [comment]
Not working on 5s but I don't see anything in the changes which should add support. It is simply more debug output. The only thing when i run it the app crashes. Not the hole phone only the app

**Comment by meyer9** [comment]
This is not working. I don't want this committed yet. Just some testing.

**Comment by coolstar** [comment]
Please do not arbitrarily submit other people's code for a pull request. The author of the commits himself has stated that the code does not work. Close the pull request.

**Comment by sgript** [comment]
This is one of the most retarded pull requests I've seen. Pull requests are for contribution, not for asking retarded questions answered repeatedly in `issues` (which mind you, should only be for issues with actual code, not first world problems). 

Close this shit.

**Comment by meyer9** [comment]
also its not his code. its mine. I didnt even know you could do that on github

**Comment by RypeDub420** [comment]
This Pull Request was not submitted by the original author.

Furthermore, the original author of the code has stated that the modified code does not work.

Please close this Pull Request.

**Pull request closed without merging**
