### PR TITLE
Better OTA Handling

### PR DESCRIPTION
**Pull request by nerdtron123**
This will backup the file if exists.

### CODE REVIEW

**Comment by mologie** [comment]
There's a handle leak in your patch. Consider using stat() or calling close() on the fd. (Not that it matters since the process dies after the jailbreak was successful.)

@meyer9:
> Currently, we are just unlinking the file. Not deleting it.
Please read the manual on what the `unlink` syscall does.

**Comment by nerdtron123** [comment]
Using unlink will delete the file on reboot?

**Comment by LordVader197** [comment]
Unlink will not delete the OTA daemon it will only be disabled in a jb state so there's no need for this commit afaik

**Comment by shdkpr2008** [comment]
@nerdtron123 Each file stored is assigned both a name and an inode number, which is an integer that is unique within the filesystem.  The directories(special type of files) associates file names with inodes. 
Unlink frees the inode of the file stored in Inode table(Dandling name also gets removed). Yes it does delete file's existence from a directory but doesn't actually do anything to the data on disk. Yet still it's not consider a best option to relink file's inode to a name after unlink. 
Mark your file gone-> using unlink will delete the file on reboot.

@LordVader197  True, OTA daemon will remains safe, it will just not start itself upon boot.

**Pull request closed without merging**
