### PR TITLE
TSMC support

### PR DESCRIPTION
**Pull request by DarknesGaming**
The iPhone 6s (TSMC) uses the N71M kernel, which has "S8003" at the end and not "S8000". I learned this while disassembling that kernel.

### CODE REVIEW

**Comment by liudayu** [comment]
You don't need to add this, the original code will work on both TSMC and Samsung chips.

Confirmed on /jailbreak

**Comment by DarknesGaming** [comment]
Ok. I will agree on you on that because I don't have anything to argue against it. I just added this as a precaution.

**Comment by chaustark** [comment]
the code already support 6s tsmc

**Comment by liudayu** [comment]
@DarknesGaming All good, you have a good day. Cheers

**Comment by Mila432** [comment]
@DarknesGaming seriously where did you find 8003

Yalu logo

**Comment by tangalbert919** [comment]
I found it inside the N71M kernel. It probably makes a difference between the Samsung A9 and the TSMC A9.

**Pull request closed without merging**
