### PR TITLE
An even better README.md

### PR DESCRIPTION
**Pull request by ryanb93**

### CODE REVIEW

**Comment by iOptimistic** [comment]
1. Nice readme, 2. It's called Yalu 102 for a reason. Yalu 10.2?? Yes.

**Comment by SuBLiNeR** [comment]
👍

**Comment by ipadkid358** [comment]
I believe this *only* supports iOS 10.2, no other versions at this time (please confirm?)
Also, I think both iPad Pro versions should be specificly mentioned (iPad Pro 9.7 inch, iPad Pro 12.9 Inch

**Comment by stefanstefan2001** [comment]
@ipadkid358  It supports up to iOS 10.2 on every other device than the iPhone 7 that's supported up to iOS 10.1.1.
Please don't ask more questions here this isn't a forum, you can go on reddit

**Pull request merged**
