### PR TITLE
Update UI text

### PR DESCRIPTION
**Pull request by daniel63194**
i think it's cooler like this.

### CODE REVIEW

**Comment by ONSOHO** [comment]
"Go" is so bored ... We need more action and some Explosions and fireworks.

**Comment by Amcio** [comment]
and power is over 9000 when you click it

**Comment by ONSOHO** [comment]
I can make a video that runs before the code after clicking, the problem would be that the scale of the video would depend on the device size

**Comment by kpwn** [comment]
current ui is to be replaced

**Comment by jonisc** [comment]
A "Slide to Jailbreak" would be nice... or something specific Yalu.

**Pull request closed without merging**
