### PR TITLE
Block accidental/automatic upgrade

### PR DESCRIPTION
**Pull request by masbog**
preventive measures for accidents upgrade

software update will be said "Unable to Check for Update"

### CODE REVIEW

**Comment by RTGDaCoder** [comment]
Sounds good. Great call

**Comment by adobasy** [comment]
Last commit by Luca disabled OTA

**Comment by bobbysn0w** [comment]
@adobasy This commit just adds apple's OTA servers to the hosts file (blocks the servers from connecting to the device)

**Comment by masbog** [comment]
@adobasy yes actually was add disable OTA, but we always can view the software update, this method by block the server is preventive measures accident tap/click install upgrade (by your friend, your family, or your child). 

look my SS, after "unlink /System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist" and disable

#127.0.0.1 mesu.apple.com
#127.0.0.1 appldnld.apple.com

then open software update...

screen shot 2017-01-28 at 10 05 06 pm

and i re-enable 
127.0.0.1 mesu.apple.com
127.0.0.1 appldnld.apple.com

screen shot 2017-01-28 at 9 05 15 pm

😄

**Comment by felipejfc** [comment]
I don't think we should mess with hosts like that in the jailbreak itself, better to do this on a cydia patch..

**Comment by nullpixel1** [comment]
@felipejfc If you check the code, luca already does it, but with other domains

**Comment by shdkpr2008** [comment]
It's a safe procedure in comparison with that of unlinking a daemon's startup service file.  Since that daemon may load anytime by calls from other daemons or programs leaving you amazed.

**Review by ThatNerdyPikachu — APPROVED** [review]
Eh,  I like it. Just adds in a good safety measure for idiots who update like on /r/jailbreak

**Comment by RajPatel0929** [comment]
agree, we need something that can work on unjb or jb phone so when does reboot unjb won't update too... I try tvos profile but still showing me there is a update

**Comment by masbog** [comment]
@RajPatel0929 if you use on unjb, try block it on your router for example in my mikrotik like this...

/ip proxy access add dst-host=apple-update-host redirect-to=127.0.0.1

**Comment by RajPatel0929** [comment]
@masbog thanks trying that now

**Comment by shdkpr2008** [comment]
It might create difficulties later in time when Saurik if update Cydia Eraser which mostly works on OTA updates.Might not be a good idea for then.

**Comment by parrotgeek1** [comment]
it DOES break cydia eraser. And downloading some things like dictionaries

**Comment by mailinglists35** [comment]
it would be nice to not have to modify stock files.

this is a cleaner method:
```
launchctl disable system/com.apple.softwareupdateservicesd
launchctl disable system/com.apple.OTATaskingAgent
launchctl disable system/com.apple.mobile.softwareupdated
```

results in forever spinning wheel checking for updates

also others say just blocking mesu.apple.com (http://www.richard-purves.com/2016/09/10/apple-services/) is enough https://www.reddit.com/r/jailbreak/comments/5r54yi/tutorial_blocking_ota_updates_without_jailbreak/

**Pull request closed without merging**
