### PR TITLE
Please go to #489

### PR DESCRIPTION
**Pull request by ohmza**
Please go to #489 instead, as this pull request does not work anymore, thanks.

### CODE REVIEW

**Comment by darkfus10n** [comment]
Ok so do we install the latest beta IPA or is there more involved? @ohmza

**Comment by ohmza** [comment]
@AdibSadman Just go and grab the fixed ipa from here -> https://github.com/ohmza/yalu102/releases/tag/119

**Comment by darkfus10n** [comment]
Thanks mate! @ohmza

**Comment by darkfus10n** [comment]
Ok so I tried the IPA but haven't noticed improvement in the success rate of rejailbreaking. Would you like me to provide any panic logs or anything? @ohmza

**Comment by ohmza** [comment]
@AdibSadman Yes, please provide me a panic log.

**Comment by darkfus10n** [comment]
[Blank 3.docx](https://github.com/kpwn/yalu102/files/908710/Blank.3.docx)

Here it is. Thanks! @ohmza

**Comment by ohmza** [comment]
@AdibSadman Can you try this new fixed ipa again -> https://github.com/ohmza/yalu102/releases/tag/119-2

**Comment by darkfus10n** [comment]
Hmm....for some reason it doesn't work at all now. Here is another panic log.
@ohmza 
[Blank 4.docx](https://github.com/kpwn/yalu102/files/908767/Blank.4.docx)

Thank you for giving up your time to help us! We really appreciate it.

**Comment by ohmza** [comment]
@AdibSadman Can you please try it this new ipa again. I also appreciate your time for testing >> https://github.com/ohmza/yalu102/releases/tag/119-3

The problem of iPad Air 2 and iPad Mini 4 were `host_page_size(mach_host_self(), &sz);` returns page size of 16384 which classifies these two devices as 16k page size devices as same as iPhone SE, iPhone 6s, iPhone 7, and iPad Pro but if you jailbreak these two devices in context of 16k devices, it would not work at all. Thus, the OP in #274 figured this problem out by forcing host_page_size of these two devices to be 4096 but it resulted in extremely low jailbreak success rate.

What I'm trying to do in 119-3 is reverting the jailbreak of these two devices to 16k page size context but using 4k address, as I think that the jailbreak success rate will be improved with 16k page size context.

**Comment by darkfus10n** [comment]
Still not working mate. Here is another panic log
[Blank 5.docx](https://github.com/kpwn/yalu102/files/908862/Blank.5.docx)

Thanks again. @ohmza

**Comment by darkfus10n** [comment]
Yep I can confirm it isn't working at all. @ohmza

**Comment by ohmza** [comment]
@AdibSadman Now, I came to the conclusion that iPad Air 2 and iPad Mini 4 cannot be jailbroken in the context of 16k memory page size at all. This new ipa, I reverted the jailbreak to the context of 4k memory page size but imitate the jailbreak process as 16k memory page size, can you please try it again -> https://github.com/ohmza/yalu102/releases/tag/119-4

**Comment by darkfus10n** [comment]
Hello. It isnt working unfortunately. But I think you're getting closer. When I press go, the device waits for a good amount of time before rebooting. @ohmza 

[Blank 6.docx](https://github.com/kpwn/yalu102/files/914936/Blank.6.docx)

**Comment by ohmza** [comment]
@AdibSadman Thank you for that information. Here is another ipa, this ipa now uses 16k memory page size address instead of 4k memory page size address -> https://github.com/ohmza/yalu102/releases/tag/119-5

**Comment by darkfus10n** [comment]
Nope. Still no luck. Exactly the same thing as before happens. @ohmza 

[Blank 7.docx](https://github.com/kpwn/yalu102/files/915300/Blank.7.docx)

**Comment by darkfus10n** [comment]
Are you sure it's something to do with the memory? Not anything else? @ohmza

**Comment by ohmza** [comment]
@AdibSadman Yes, as the original method that make the jailbreak working was; forcing the memory page size to 4096 although `host_page_size(mach_host_self(), &sz);` returns the memory page size of 16384. The original fix was discussing on #274

**Comment by darkfus10n** [comment]
Hi @ohmza I cannot find the IPA. Can you provide me the link again please? @ohmza

**Comment by Mila432** [comment]
just forget it your pr is not working

**Comment by ccfman2004** [comment]
Anyone have the ipa?  I cannot figure out how to compile it.

**Comment by ohmza** [comment]
Okay, I'm going to close this pull request for now as the problem that affects iPad Air 2 and iPad Mini 4 jailbreak success rate can't be fixed. But soon, I will create another pull request that contains the working stuffs only which is:

- Implemented more efficient OTA disabler method
- Bundled SCP, SFTP and OpenSSL binaries

The reason that I have to do this because the code is messed up on this pull request. Thank you for all of your supporting.

**Pull request closed without merging**
