### PR TITLE
fixed offsets, removed dups, added all iptv4g

### PR DESCRIPTION
**Pull request by Mila432**

### CODE REVIEW

**Comment by mwoolweaver** [comment]
I like the way this looks a lot better. Also removes some redundant info

**Comment by mwoolweaver** [comment]
Also I noticed 2 missing board configs they are listed below.

S8003
S5L8965

**Comment by Mila432** [comment]
@mwoolweaver  there is no s8003

**Comment by mwoolweaver** [comment]
Are you saying the OS doesn't discriminate between the S8001 and S8003 like it does the [iPad Air's S5L8965](https://www.theiphonewiki.com/wiki/S5L8965) and the S5L8960 found in the 5S

Or you're saying it doesn't exist?

**Comment by Mila432** [comment]
@mwoolweaver cpu has nothing to do with the kernel , and there are only 5 kernel versions for all devices as of now (arm64)

**Comment by KILLCAMPER** [comment]
@Mila432  Are the iPad Air 2 cellular same off set a Air 2 wifi as only see wifi in code

**Comment by RypeDub420** [comment]
@Mila432 Would you like me to copy your changes to my fork, then add the comments for which device each offset is targeting?

Could you also help me by simply saying this line in the code targets this device? Then I'll make it pretty in the comments with just one line now that you've added a full shoutout at the top.

**Comment by Ale9219** [comment]
hello can you add offsets for ipad air wifi lte

**Comment by Mila432** [comment]
@Ale9219 retards should stay away

**Comment by RypeDub420** [comment]
@Ale9219 The team already has all the necessary offsets to support EVERY DEVICE.

STOP SUBMITTING PULL REQUESTS FOR OFFSETS !!!!

THEY WILL BE INSTANTLY CLOSED!!!!!!!!!!!!

**Pull request merged**
