### PR TITLE
add iPad mini 2 (Wi-Fi) on 10.2

### PR DESCRIPTION
**Pull request by Defying**
should work, stops at `got a cpacr` due to lack of 4k device support so can't fully test atm

### CODE REVIEW

**Comment by KILLCAMPER** [comment]
Is the off set same for iPad Air 2 cellular thanks

**Comment by AdibSadman** [comment]
Please don't forget to add support for iPad Air 2 WiFi.

Thanks

**Comment by JoeGodz** [comment]
Can you add iPhone 6 support as well?

**Comment by AGagarin** [comment]
How did you find the offsets. ? I have cellular version of iPad Mini 2 and would like to find the offsets by myself

**Comment by bao3** [comment]
I have ipad mini2 LTE , so how to find offsets ?

**Comment by maguanghui** [comment]
Please don't forget to add support for iPad Air 2 WiFi.
Thank you very very much

**Comment by iKilledAppl3** [comment]
@JoeGodz offsets for the iPhone 6 and iPod touch 6 are similar and if you look at the code in offsets.c they are there. The reason why it's not working is because at the moment Yalu doesn't quite support 4k devices as stated by qwerty.

**Comment by JoeGodz** [comment]
Thanks @iKilledAppl3. I saw the code after I commented. Hopefully, this will all be dealt with by the end of this weekend. I'm "following" the 4k devices conversation in the issues tab.

**Comment by JoeGodz** [comment]
I also have an iPad mini 2, so if anyone has something they would like me to test, I have plenty of free time to do so.

**Comment by RypeDub420** [comment]
@Mila432 has already made modifications to the offsets.h/.c file(s) which include support for all devices, and it got accepted and merged with the master. Please close this pull request.

**Pull request closed without merging**
